//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package ford.application.attachment.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Meta data and actual attachments.
 * 
 * <p>Java class for ApplicationAttachmentInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationAttachmentInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ford/Application/Attachment/v1.0}AttachmentApplication"/>
 *         &lt;element ref="{urn:ford/Application/Attachment/v1.0}Attachments"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationAttachmentInfoType", propOrder = {
    "attachmentApplication",
    "attachments"
})
public class ApplicationAttachmentInfoType {

    @XmlElement(name = "AttachmentApplication", required = true)
    protected AttachmentApplicationType attachmentApplication;
    @XmlElement(name = "Attachments", required = true)
    protected AttachmentsType attachments;

    /**
     * Gets the value of the attachmentApplication property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentApplicationType }
     *     
     */
    public AttachmentApplicationType getAttachmentApplication() {
        return attachmentApplication;
    }

    /**
     * Sets the value of the attachmentApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentApplicationType }
     *     
     */
    public void setAttachmentApplication(AttachmentApplicationType value) {
        this.attachmentApplication = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentsType }
     *     
     */
    public AttachmentsType getAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentsType }
     *     
     */
    public void setAttachments(AttachmentsType value) {
        this.attachments = value;
    }

}
