//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package ford.application.attachment.v1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This entity has the application specific information to which this Attachment Service interacts with.
 * 
 * <p>Java class for AttachmentApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttachmentApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApplicationID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="EntityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{urn:ford/Application/Attachment/v1.0}EntityAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttachmentApplicationType", propOrder = {
    "applicationID",
    "entityName",
    "entityAttributes"
})
public class AttachmentApplicationType {

    @XmlElement(name = "ApplicationID", required = true)
    protected BigInteger applicationID;
    @XmlElement(name = "EntityName", required = true)
    protected String entityName;
    @XmlElement(name = "EntityAttributes")
    protected EntityAttributesType entityAttributes;

    /**
     * Gets the value of the applicationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApplicationID() {
        return applicationID;
    }

    /**
     * Sets the value of the applicationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApplicationID(BigInteger value) {
        this.applicationID = value;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * gets inserted /updated.
     * 
     * @return
     *     possible object is
     *     {@link EntityAttributesType }
     *     
     */
    public EntityAttributesType getEntityAttributes() {
        return entityAttributes;
    }

    /**
     * Sets the value of the entityAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityAttributesType }
     *     
     */
    public void setEntityAttributes(EntityAttributesType value) {
        this.entityAttributes = value;
    }

}
