//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package ford.application.attachment.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ford.application.attachment.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Attachment_QNAME = new QName("urn:ford/Application/Attachment/v1.0", "Attachment");
    private final static QName _AttachmentSearchResults_QNAME = new QName("urn:ford/Application/Attachment/v1.0", "AttachmentSearchResults");
    private final static QName _Attachments_QNAME = new QName("urn:ford/Application/Attachment/v1.0", "Attachments");
    private final static QName _AttachmentSearchCriteria_QNAME = new QName("urn:ford/Application/Attachment/v1.0", "AttachmentSearchCriteria");
    private final static QName _AttachmentApplication_QNAME = new QName("urn:ford/Application/Attachment/v1.0", "AttachmentApplication");
    private final static QName _ApplicationAttachmentInfo_QNAME = new QName("urn:ford/Application/Attachment/v1.0", "ApplicationAttachmentInfo");
    private final static QName _EntityAttributes_QNAME = new QName("urn:ford/Application/Attachment/v1.0", "EntityAttributes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ford.application.attachment.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationAttachmentInfoType }
     * 
     */
    public ApplicationAttachmentInfoType createApplicationAttachmentInfoType() {
        return new ApplicationAttachmentInfoType();
    }

    /**
     * Create an instance of {@link AttachmentSearchCriteriaType }
     * 
     */
    public AttachmentSearchCriteriaType createAttachmentSearchCriteriaType() {
        return new AttachmentSearchCriteriaType();
    }

    /**
     * Create an instance of {@link AttachmentSearchResultsType }
     * 
     */
    public AttachmentSearchResultsType createAttachmentSearchResultsType() {
        return new AttachmentSearchResultsType();
    }

    /**
     * Create an instance of {@link AttachmentsType }
     * 
     */
    public AttachmentsType createAttachmentsType() {
        return new AttachmentsType();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link EntityAttributesType }
     * 
     */
    public EntityAttributesType createEntityAttributesType() {
        return new EntityAttributesType();
    }

    /**
     * Create an instance of {@link AttachmentApplicationType }
     * 
     */
    public AttachmentApplicationType createAttachmentApplicationType() {
        return new AttachmentApplicationType();
    }

    /**
     * Create an instance of {@link EntityAttributeType }
     * 
     */
    public EntityAttributeType createEntityAttributeType() {
        return new EntityAttributeType();
    }

    /**
     * Create an instance of {@link AttachmentSearchResult }
     * 
     */
    public AttachmentSearchResult createAttachmentSearchResult() {
        return new AttachmentSearchResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ford/Application/Attachment/v1.0", name = "Attachment")
    public JAXBElement<AttachmentType> createAttachment(AttachmentType value) {
        return new JAXBElement<AttachmentType>(_Attachment_QNAME, AttachmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentSearchResultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ford/Application/Attachment/v1.0", name = "AttachmentSearchResults")
    public JAXBElement<AttachmentSearchResultsType> createAttachmentSearchResults(AttachmentSearchResultsType value) {
        return new JAXBElement<AttachmentSearchResultsType>(_AttachmentSearchResults_QNAME, AttachmentSearchResultsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ford/Application/Attachment/v1.0", name = "Attachments")
    public JAXBElement<AttachmentsType> createAttachments(AttachmentsType value) {
        return new JAXBElement<AttachmentsType>(_Attachments_QNAME, AttachmentsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentSearchCriteriaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ford/Application/Attachment/v1.0", name = "AttachmentSearchCriteria")
    public JAXBElement<AttachmentSearchCriteriaType> createAttachmentSearchCriteria(AttachmentSearchCriteriaType value) {
        return new JAXBElement<AttachmentSearchCriteriaType>(_AttachmentSearchCriteria_QNAME, AttachmentSearchCriteriaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentApplicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ford/Application/Attachment/v1.0", name = "AttachmentApplication")
    public JAXBElement<AttachmentApplicationType> createAttachmentApplication(AttachmentApplicationType value) {
        return new JAXBElement<AttachmentApplicationType>(_AttachmentApplication_QNAME, AttachmentApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationAttachmentInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ford/Application/Attachment/v1.0", name = "ApplicationAttachmentInfo")
    public JAXBElement<ApplicationAttachmentInfoType> createApplicationAttachmentInfo(ApplicationAttachmentInfoType value) {
        return new JAXBElement<ApplicationAttachmentInfoType>(_ApplicationAttachmentInfo_QNAME, ApplicationAttachmentInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ford/Application/Attachment/v1.0", name = "EntityAttributes")
    public JAXBElement<EntityAttributesType> createEntityAttributes(EntityAttributesType value) {
        return new JAXBElement<EntityAttributesType>(_EntityAttributes_QNAME, EntityAttributesType.class, null, value);
    }

}
