//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

package ford._interface.application.attachment.v1;

import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ApplicationAttachmentService",
    targetNamespace = "urn:ford/interface/Application/Attachment/v1.0")
@HandlerChain(file = "wsc-handler-consumer.xml")
public class ApplicationAttachmentService
        extends Service {

    private final static URL APPLICATIONATTACHMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPLICATIONATTACHMENTSERVICE_EXCEPTION;
    private final static QName APPLICATIONATTACHMENTSERVICE_QNAME = new QName(
            "urn:ford/interface/Application/Attachment/v1.0", "ApplicationAttachmentService");

    static {
        WebServiceException e = null;
        APPLICATIONATTACHMENTSERVICE_WSDL_LOCATION = ApplicationAttachmentService.class
                .getResource("/META-INF/wsdl/ApplicationAttachment.wsdl");
        if (APPLICATIONATTACHMENTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException(
                    "Cannot find 'META-INF/wsdl/ApplicationAttachment.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        APPLICATIONATTACHMENTSERVICE_EXCEPTION = e;
    }

    public ApplicationAttachmentService() {
        super(__getWsdlLocation(), APPLICATIONATTACHMENTSERVICE_QNAME);
    }

    public ApplicationAttachmentService(final URL wsdlLocation) {
        super(wsdlLocation, APPLICATIONATTACHMENTSERVICE_QNAME);
    }

    public ApplicationAttachmentService(final URL wsdlLocation, final QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *         returns IApplicationAttachment
     */
    @WebEndpoint(name = "ApplicationAttachment")
    public IApplicationAttachment getApplicationAttachment() {
        return super.getPort(new QName("urn:ford/interface/Application/Attachment/v1.0",
                "ApplicationAttachment"), IApplicationAttachment.class);
    }

    /**
     *
     * @param features
     *        A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *        Supported features not in the <code>features</code> parameter will have their
     *        default values.
     * @return
     *         returns IApplicationAttachment
     */
    @WebEndpoint(name = "ApplicationAttachment")
    public IApplicationAttachment getApplicationAttachment(
            final WebServiceFeature... features) {
        return super.getPort(new QName("urn:ford/interface/Application/Attachment/v1.0",
                "ApplicationAttachment"), IApplicationAttachment.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPLICATIONATTACHMENTSERVICE_EXCEPTION != null) {
            throw APPLICATIONATTACHMENTSERVICE_EXCEPTION;
        }
        return APPLICATIONATTACHMENTSERVICE_WSDL_LOCATION;
    }

}
