//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

/**
 * 
 *         Service definition for the Generic Application Attachment service.
 *         Entity name (EDM Alignment): Application
 * 	    Business Qualifier: Attachment
 * 	    Resulting Service Name: ApplicationAttachment
 *     
 * 
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ford/interface/Application/Attachment/v1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ford._interface.application.attachment.v1;
